<?php

namespace SoftUniBlogBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
//    public function addUserRole(USer){
//        $sql='INSERT INTO users_roles
//              '
//    }
}
